# Header
menu:
  首页: /
  归档: /archives
  关于: /about
  简历: /resume
rss: /atom.xml
github: https://github.com/zuobaiquan
logo_title: MyLogo
blog_title: 热爱前端喜欢分享的程序猿


menu_icons:
  enable: true
  #KeyMapsToMenuItemKey: NameOfTheIconFromFontAwesome
  home: home
  about: user
  categories: th
  tags: tags
  archives: calendar-check-o
  commonweal: heartbeat
  resume: heart


# Content
excerpt_link: Read More
fancybox: true
mathjax: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- tag
- links
#- tagcloud
#- zhifubao
#- rss

font:
  enable: true

  # Uri of fonts host. E.g. //fonts.googleapis.com (Default)
  host:

  # Global font settings used on <body> element.
  global:
    # external: true will load this font family from host.
    external: true
    family: Lato

  # Font settings for Headlines (h1, h2, h3, h4, h5, h6)
  # Fallback to `global` font settings.
  headings:
    external: true
    family:

  # Font settings for posts
  # Fallback to `global` font settings.
  posts:
    external: true
    family:

  # Font settings for Logo
  # Fallback to `global` font settings.
  # The `size` option use `px` as unit
  logo:
    external: true
    family:
    size:

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family:

links_title: 友情链接
links_layout: block
#links_layout: inline-block
links_icon: link
links:
  张鑫旭: http://www.zhangxinxu.com/
  张雯丽: http://zhangwenli.com/
  廖雪峰: http://www.liaoxuefeng.com/wiki/001434446689867b27157e896e74d51a89c25cc8b43bdb3000
  阮一峰: http://www.ruanyifeng.com/blog/archives.html




# Miscellaneous
wx_block: false
google_analytics:
favicon: /img/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# Duoshuo
duoshuo_shortname:

# Swiftype Search
swiftype_key:
